"""add backtests tables

Revision ID: 4844b721ae30
Revises: eed1ac69007e
Create Date: 2025-09-23 17:30:06.954051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4844b721ae30'
down_revision: Union[str, Sequence[str], None] = 'eed1ac69007e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('strategy_type', sa.String(length=32), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_positions_backtest_id'), 'daily_positions', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_daily_positions_date'), 'daily_positions', ['date'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id', 'name', name='uq_metric_per_backtest')
    )
    op.create_index(op.f('ix_metrics_backtest_id'), 'metrics', ['backtest_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_backtest_id'), 'trades', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_trades_date'), 'trades', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_backtest_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_metrics_backtest_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_daily_positions_date'), table_name='daily_positions')
    op.drop_index(op.f('ix_daily_positions_backtest_id'), table_name='daily_positions')
    op.drop_table('daily_positions')
    op.drop_table('backtests')
    # ### end Alembic commands ###
